### ISSUE TITLE
HTTP status 204 should not be considered an error

### ISSUE THREAD

**Issue by alvarolopez** [EGI-FCTF/rOCCI-cli#15]
If an empty response is produced (for example in a DELETE) the OCCI implementation can return a response with a 204 status. A status 200 with an empty response is also fine, but the 204 should not be considered as an error.

**Comment by arax** [comment]
Agreed. Will fix.

**Comment by spinto** [comment]
I am out of the office until 11/11/2015.

For urgent matter, you can contact the TEP Core Team (tepcoreteam@esa.int).


Note: This is an automated response to your message  "Re: [rOCCI-cli] HTTP
status 204 should not be considered an error (#15)" sent on 10/23/2015
22:25:51.

This is the only notification you will receive while this person is away.


This message and any attachments are intended for the use of the addressee or addressees only.
The unauthorised disclosure, use, dissemination or copying (either in whole or in part) of its
content is not permitted.
If you received this message in error, please notify the sender and delete it from your system.
Emails can be altered and their integrity cannot be guaranteed by the sender.

Please consider the environment before printing this email.

**Comment by enolfc** [comment]
Is this already released? Apparently it is also failing in the case of listing resources

[...]
GET /occi1.1/storage/ HTTP/1.1\r\nAccept: text/uri-list\r\nUser-Agent: rOCCI-core/4.3.2 rOCCI-api/4.3.4 OCCI/1.1 ruby-x86_64-linux/2.1.5p273\r\nX-Auth-Token: XXX\r\nConnection: close\r\nHost: cloud.ifca.es:8787\r\n\r\n"
-> "HTTP/1.1 204 No Content\r\n"
-> "Date: Thu, 07 Jul 2016 12:31:00 GMT\r\n"
-> "Content-Type: text/uri-list; charset=utf8\r\n"
-> "Content-Length: 0\r\n"
-> "Connection: close\r\n"
-> "server: ooi/0.1.1 OCCI/1.1\r\n"
-> "x-compute-request-id: req-ae9cb54b-ae9d-4e5b-82c0-cf6b5ab61a33\r\n"
-> "\r\n"
Conn close
F, [2016-07-07T12:31:00.081269 #1] FATAL -- : [rOCCI-cli] An error occurred! Message: HTTP GET failed! HTTP Response status: [204] No Content
/opt/occi-cli/embedded/lib/ruby/gems/2.1.0/gems/occi-api-4.3.4/lib/occi/api/client/client_http.rb:81:in `list': HTTP GET failed! HTTP Response status: [204] No Content (RuntimeError)
	from /opt/occi-cli/embedded/lib/ruby/gems/2.1.0/gems/occi-api-4.3.4/lib/occi/api/dsl/main_methods.rb:12:in `list'
	from /opt/occi-cli/embedded/lib/ruby/gems/2.1.0/gems/occi-cli-4.3.3/lib/occi/cli/helpers/list_helper.rb:8:in `helper_list'
	from /opt/occi-cli/embedded/lib/ruby/gems/2.1.0/gems/occi-cli-4.3.3/bin/occi:140:in `<top (required)>'
	from /usr/bin/occi:23:in `load'
	from /usr/bin/occi:23:in `<main>'

**Comment by arax** [comment]
You are using an outdated client. Please, use [1]. If you can confirm that everything works, I will make it the next stable release.

[1] https://appdb.egi.eu/store/software/rocci.cli/releases/4.3.x/v4.3.4-1/

**Comment by enolfc** [comment]
Sorry for the noise, it does work with the pre-release.

Thanks,
Enol
