### ISSUE TITLE
Doubt about VOMs authentication

### ISSUE THREAD

**Issue by giovannifs** [EGI-FCTF/rOCCI-cli#17]
Hi everyone,

I'm trying to use voms authentication and something is not working out.
I have an occi implementation configured with self-signed certificate and I'm using the server certificate as ca-path at rocci-cli call. I think it should work, right?

I'm doing this call
```
occi --endpoint http://$HOST:8182 --auth x509 --user-cred /tmp/x509up_u1134 --voms --action describe --resource compute --ca-path $PATH -d
```

Consider that server certificate is inside $PATH folder. The output was:
```
[2015-11-05T12:28:51.722697 #8877] FATAL -- : [rOCCI-cli] An SSL error occurred! Please, make sure your credentials are valid and recognized by the endpoint! Message: SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed
/usr/lib/ruby/1.9.1/net/http.rb:799:in `connect': SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed (OpenSSL::SSL::SSLError)
from /usr/lib/ruby/1.9.1/net/http.rb:799:in `block in connect'
from /usr/lib/ruby/1.9.1/timeout.rb:54:in `timeout'
from /usr/lib/ruby/1.9.1/timeout.rb:99:in `timeout'
from /usr/lib/ruby/1.9.1/net/http.rb:799:in `connect'
from /usr/lib/ruby/1.9.1/net/http.rb:755:in `do_start'
from /usr/lib/ruby/1.9.1/net/http.rb:744:in `start'
from /usr/lib/ruby/1.9.1/net/http.rb:1284:in `request'
from /var/lib/gems/1.9.1/gems/httparty-0.13.1/lib/httparty/request.rb:93:in `perform'
from /var/lib/gems/1.9.1/gems/httparty-0.13.1/lib/httparty.rb:521:in `perform_request'
from /var/lib/gems/1.9.1/gems/httparty-0.13.1/lib/httparty.rb:473:in `post'
from /var/lib/gems/1.9.1/gems/occi-api-4.3.2/lib/occi/api/client/http/authn_plugins/keystone.rb:63:in `set_auth_token'
from /var/lib/gems/1.9.1/gems/occi-api-4.3.2/lib/occi/api/client/http/authn_plugins/keystone.rb:19:in `setup'
from /var/lib/gems/1.9.1/gems/occi-api-4.3.2/lib/occi/api/client/http/helpers.rb:39:in `get_auth'
from /var/lib/gems/1.9.1/gems/occi-api-4.3.2/lib/occi/api/client/http/helpers.rb:56:in `rescue in preauthenticate'
from /var/lib/gems/1.9.1/gems/occi-api-4.3.2/lib/occi/api/client/http/helpers.rb:46:in `preauthenticate'
from /var/lib/gems/1.9.1/gems/occi-api-4.3.2/lib/occi/api/client/client_base.rb:44:in `initialize'
from /var/lib/gems/1.9.1/gems/occi-api-4.3.2/lib/occi/api/client/client_http.rb:46:in `initialize'
from /var/lib/gems/1.9.1/gems/occi-api-4.3.2/lib/occi/api/dsl.rb:17:in `new'
from /var/lib/gems/1.9.1/gems/occi-api-4.3.2/lib/occi/api/dsl.rb:17:in `connect'
```

At our occi implementation, the generated token will be the client certificate normalized. Then, we're trying to get the client certificate at server side without success.

We also try to use -s option at rocci-cli to not validate the server certificate, in this case, does rocci-cli send the client cert to server? I'm questioning because we can't get it at server side while using -s option.

We'd appreciate your help!

**Comment by arax** [comment]
Hi @giovannifs 
can you try accessing the server with `openssl`?
```bash
openssl s_client $HOST:$PORT -CApath $PATH -cert /tmp/x509up_u1134 -key /tmp/x509up_u1134
```
This will output a lot of details about the certificate validation process and is usually quite helpful. Also, please, make sure that `$HOST` and `$PORT` in this `openssl` command point to your Keystone (or its equivalent in your installation) and not to your OCCI server. The error was raised
```
from /var/lib/gems/1.9.1/gems/occi-api-4.3.2/lib/occi/api/client/http/authn_plugins/keystone.rb:63:in `set_auth_token'
from /var/lib/gems/1.9.1/gems/occi-api-4.3.2/lib/occi/api/client/http/authn_plugins/keystone.rb:19:in `setup'
from /var/lib/gems/1.9.1/gems/occi-api-4.3.2/lib/occi/api/client/http/helpers.rb:39:in `get_auth'
```
and that means it happened after the redirect (you should be able to see that in rOCCI-cli's debug log).

The `-s` option will turn off peer verification in OpenSSL, it should not affect the authentication process itself.

If you need help or more information, please, send me a private e-mail (the address is in my GH profile).

**Comment by spinto** [comment]
I am out of the office until 11/11/2015.

For urgent matter, you can contact the TEP Core Team (tepcoreteam@esa.int).


Note: This is an automated response to your message  "Re: [rOCCI-cli] Doubt
about VOMs authentication (#17)" sent on 11/5/2015 19:46:06.

This is the only notification you will receive while this person is away.


This message and any attachments are intended for the use of the addressee or addressees only.
The unauthorised disclosure, use, dissemination or copying (either in whole or in part) of its
content is not permitted.
If you received this message in error, please notify the sender and delete it from your system.
Emails can be altered and their integrity cannot be guaranteed by the sender.

Please consider the environment before printing this email.

**Comment by spinto** [comment]
I am out of the office until 11/11/2015.

For urgent matter, you can contact the TEP Core Team (tepcoreteam@esa.int).


Note: This is an automated response to your message  "[rOCCI-cli] Doubt about
VOMs authentication (#17)" sent on 11/5/2015 19:29:54.

This is the only notification you will receive while this person is away.


This message and any attachments are intended for the use of the addressee or addressees only.
The unauthorised disclosure, use, dissemination or copying (either in whole or in part) of its
content is not permitted.
If you received this message in error, please notify the sender and delete it from your system.
Emails can be altered and their integrity cannot be guaranteed by the sender.

Please consider the environment before printing this email.

**Comment by spinto** [comment]
I am out of the office until 11/11/2015.

For urgent matter, you can contact the TEP Core Team (tepcoreteam@esa.int).


Note: This is an automated response to your message  "Re: [rOCCI-cli] Doubt
about VOMs authentication (#17)" sent on 11/5/2015 19:45:22.

This is the only notification you will receive while this person is away.


This message and any attachments are intended for the use of the addressee or addressees only.
The unauthorised disclosure, use, dissemination or copying (either in whole or in part) of its
content is not permitted.
If you received this message in error, please notify the sender and delete it from your system.
Emails can be altered and their integrity cannot be guaranteed by the sender.

Please consider the environment before printing this email.
