### ISSUE TITLE
Error while describing resource

### ISSUE THREAD

**Issue by giovannifs** [EGI-FCTF/rOCCI-cli#18]
Hi @arax ,

I'm trying to use new authentication method called by token and I'm having a problem when describe the resource. I've created the resource with the bellow command:
```
 occi --media-type text/occi --endpoint http://$ENDPOINT --action create --mixin resource_tpl#m1-small --mixin os_tpl#fbc85206-fbcc-4ad9-ae93-54946fdd5df7 --resource compute --attribute occi.core.title="my test" --auth token --token "$TOKEN"
```

But when I try to describe the resource with the command:
```
occi --debug --endpoint http://$ENDPOINT --auth token --action describe --resource /compute/$INSTANCE_ID --token "$TOKEN"
```

I have the following error (this is part of debug message):

```
-> "Category: compute; scheme=\"http://schemas.ogf.org/occi/infrastructure#\"; class=\"kind\"; title=\"Compute Resource\"; rel=\"http://schemas.ogf.org/occi/core#resource\"; location=\"http://localhost:8182/compute/\"; attributes=\"occi.compute.architecture occi.compute.state{immutable} occi.compute.speed occi.compute.memory occi.compute.cores occi.compute.hostname\"; actions=\"http://schemas.ogf.org/occi/infrastructure/compute/action#start http://schemas.ogf.org/occi/infrastructure/compute/action#stop http://schemas.ogf.org/occi/infrastructure/compute/action#restart http://schemas.ogf.org/occi/infrastructure/compute/action#suspend\"\nCategory: m1-small; scheme=\"http://schemas.openstack.org/template/resource#\"; class=\"mixin\"; title=\"Flavor: m1.small \"; rel=\"http://schemas.ogf.org/occi/infrastructure#resource_tpl\"; location=\"http://localhost:8787/m1-small/\"\nCategory: fbc85206-fbcc-4ad9-ae93-54946fdd5df7; scheme=\"http://schemas.openstack.org/template/os#\"; class=\"mixin\"; title=\"Image: cirros-0.3.1-x86_64-uec\"; rel=\"http://schemas.ogf.org/occi/infrastructure#os_tpl\"; location=\"http://localhost:8787/fbc85206-fbcc-4ad9-ae93-54946fdd5df7/\"\nCategory: link; scheme=\"http://schemas.ogf.org/occi/core#\"; class=\"kind\"; title=\"Link\"; rel=\"http://schemas.ogf.org/occi/core#entity\"; location=\"http://localhost:8182/link/\"; attributes=\"occi.core.source occi.core.target\"\nCategory: networkinterface; scheme=\"http://schemas.ogf.org/occi/infrastructure#\"; class=\"kind\"; title=\"A L2 Network Interface\"; rel=\"http://schemas.ogf.org/occi/core#link\"; location=\"http://localhost:8787/network/interface/\"; attributes=\"occi.networkinterface.interface{immutable} occi.networkinterface.mac occi.networkinterface.state{immutable}\"\nLink: /network/interface/35ccceb3-9872-44ee-878a-d6298aa11769; occi.networkinterface.gateway=\"Not defined\"; occi.networkinterface.state=\"active\"; occi.networkinterface.address=\"150.165.15.81:10006\"; occi.networkinterface.mac=\"Not defined\"; occi.networkinterface.interface=\"eth0\"; occi.core.id=\"/network/interface/35ccceb3-9872-44ee-878a-d6298aa11769\"; occi.core.target=\"/network/public\"; occi.networkinterface.allocation=\"static\"; occi.core.source=\"/compute/federated_instance_089d406b-f57e-47f8-ae20-b37bf9e319c9\"\nX-OCCI-Attribute: occi.compute.state=\"active\"\nX-OCCI-Attribute: occi.compute.hostname=\"fogbow-instance-e0f322c3-ad87-4034-91dd-a3f64e9ae281\"\nX-OCCI-Attribute: org.fogbowcloud.request.ssh-username=\"fogbow\"\nX-OCCI-Attribute: occi.compute.memory=\"2.0\"\nX-OCCI-Attribute: org.fogbowcloud.request.extra-ports=\"{}\"\nX-OCCI-Attribute: occi.compute.cores=\"1\"\nX-OCCI-Attribute: org.fogbowcloud.request.ssh-public-address=\"150.165.15.81:10006\"\nX-OCCI-Attribute: occi.core.id=\"bc150132-1b8b-45ab-b28e-6b7c0c9aac73\"\nX-OCCI-Attribute: occi.compute.architecture=\"Not defined\"\nX-OCCI-Attribute: occi.compute.speed=\"Not defined\""
read 2827 bytes
Conn close
D, [2016-01-20T20:58:01.970692 #11210] DEBUG -- : [rOCCI-api] Response from location: "/compute/federated_instance_089d406b-f57e-47f8-ae20-b37bf9e319c9"
D, [2016-01-20T20:58:01.973591 #11210] DEBUG -- : [rOCCI-api] Response should contain kind: "http://schemas.ogf.org/occi/infrastructure#compute"
D, [2016-01-20T20:58:01.973847 #11210] DEBUG -- : [rOCCI-api] Parser call: "text/plain" false Occi::Core::Resource {"content-type"=>["text/plain; charset=UTF-8"], "content-length"=>["2827"], "server"=>["Restlet-Framework/2.2.0"], "accept-ranges"=>["bytes"], "vary"=>["Accept-Charset, Accept-Encoding, Accept-Language, Accept"], "date"=>["Wed, 20 Jan 2016 21:01:01 GMT"]}
D, [2016-01-20T20:58:01.973975 #11210] DEBUG -- : [rOCCI-core] [Occi::Parser] Parsing request data to OCCI Collection
D, [2016-01-20T20:58:01.974342 #11210] DEBUG -- : [rOCCI-core] [Occi::Parser] Parsing headers: []
D, [2016-01-20T20:58:01.974408 #11210] DEBUG -- : [rOCCI-core] [Occi::Parser] Parsing a resource from headers
D, [2016-01-20T20:58:01.974468 #11210] DEBUG -- : [rOCCI-core] [Occi::Parser::Text] Parsing through Occi::Parser::Text.resource
D, [2016-01-20T20:58:01.974618 #11210] DEBUG -- : [rOCCI-core] [Occi::Model] Registering OCCI Core categories enitity, resource and link
D, [2016-01-20T20:58:01.974685 #11210] DEBUG -- : [rOCCI-core] [Occi::Model] Registering category http://schemas.ogf.org/occi/core#entity
D, [2016-01-20T20:58:01.974818 #11210] DEBUG -- : [rOCCI-core] [Occi::Model] Registering category http://schemas.ogf.org/occi/core#resource
D, [2016-01-20T20:58:01.974964 #11210] DEBUG -- : [rOCCI-core] [Occi::Model] Registering category http://schemas.ogf.org/occi/core#link
D, [2016-01-20T20:58:01.976252 #11210] DEBUG -- : [rOCCI-core] [Occi::Core::Attributes] Skipping pattern checks on attributes, turn off the compatibility mode and enable the attribute pattern check in settings!
D, [2016-01-20T20:58:01.976414 #11210] DEBUG -- : [rOCCI-core] [Occi::Parser] Parsing text/plain from body
D, [2016-01-20T20:58:01.976553 #11210] DEBUG -- : [rOCCI-core] [Occi::Model] Registering OCCI Core categories enitity, resource and link
D, [2016-01-20T20:58:01.976618 #11210] DEBUG -- : [rOCCI-core] [Occi::Model] Registering category http://schemas.ogf.org/occi/core#entity
D, [2016-01-20T20:58:01.976738 #11210] DEBUG -- : [rOCCI-core] [Occi::Model] Registering category http://schemas.ogf.org/occi/core#resource
D, [2016-01-20T20:58:01.977617 #11210] DEBUG -- : [rOCCI-core] [Occi::Model] Registering category http://schemas.ogf.org/occi/core#link
D, [2016-01-20T20:58:01.978224 #11210] DEBUG -- : [rOCCI-core] [Occi::Parser::Text] Parsing through Occi::Parser::Text.resource
D, [2016-01-20T20:58:01.978616 #11210] DEBUG -- : [rOCCI-core] [Occi::Model] Registering OCCI Core categories enitity, resource and link
D, [2016-01-20T20:58:01.978834 #11210] DEBUG -- : [rOCCI-core] [Occi::Model] Registering category http://schemas.ogf.org/occi/core#entity
D, [2016-01-20T20:58:01.979313 #11210] DEBUG -- : [rOCCI-core] [Occi::Model] Registering category http://schemas.ogf.org/occi/core#resource
D, [2016-01-20T20:58:01.979718 #11210] DEBUG -- : [rOCCI-core] [Occi::Model] Registering category http://schemas.ogf.org/occi/core#link
D, [2016-01-20T20:58:01.980818 #11210] DEBUG -- : [rOCCI-core] [Occi::Core::Attributes] Skipping pattern checks on attributes, turn off the compatibility mode and enable the attribute pattern check in settings!
D, [2016-01-20T20:58:01.981106 #11210] DEBUG -- : [rOCCI-core] [Occi::Parser::Text] Parsing through Occi::Parser::Text.category
D, [2016-01-20T20:58:01.987998 #11210] DEBUG -- : [rOCCI-core] [Occi::Parser::Text] class "kind" identified as kind
D, [2016-01-20T20:58:01.990231 #11210] DEBUG -- : [rOCCI-core] [Occi::Core::Attributes] Skipping pattern checks on attributes, turn off the compatibility mode and enable the attribute pattern check in settings!
D, [2016-01-20T20:58:01.990476 #11210] DEBUG -- : [rOCCI-core] [Occi::Parser::Text] Parsing through Occi::Parser::Text.category
D, [2016-01-20T20:58:01.994923 #11210] DEBUG -- : [rOCCI-core] [Occi::Parser::Text] class "mixin" identified as mixin
D, [2016-01-20T20:58:01.995300 #11210] DEBUG -- : [rOCCI-core] [Occi::Parser::Text] Parsing through Occi::Parser::Text.category
D, [2016-01-20T20:58:01.999764 #11210] DEBUG -- : [rOCCI-core] [Occi::Parser::Text] class "mixin" identified as mixin
D, [2016-01-20T20:58:02.000123 #11210] DEBUG -- : [rOCCI-core] [Occi::Parser::Text] Parsing through Occi::Parser::Text.category
D, [2016-01-20T20:58:02.005162 #11210] DEBUG -- : [rOCCI-core] [Occi::Parser::Text] class "kind" identified as kind
D, [2016-01-20T20:58:02.006104 #11210] DEBUG -- : [rOCCI-core] [Occi::Core::Attributes] Skipping pattern checks on attributes, turn off the compatibility mode and enable the attribute pattern check in settings!
D, [2016-01-20T20:58:02.007412 #11210] DEBUG -- : [rOCCI-core] [Occi::Parser::Text] Parsing through Occi::Parser::Text.category
D, [2016-01-20T20:58:02.012767 #11210] DEBUG -- : [rOCCI-core] [Occi::Parser::Text] class "kind" identified as kind
D, [2016-01-20T20:58:02.014895 #11210] DEBUG -- : [rOCCI-core] [Occi::Core::Attributes] Skipping pattern checks on attributes, turn off the compatibility mode and enable the attribute pattern check in settings!
D, [2016-01-20T20:58:02.016215 #11210] DEBUG -- : [rOCCI-core] [Occi::Parser::Text] Parsing through Occi::Parser::Text.link_string
F, [2016-01-20T20:58:02.020992 #11210] FATAL -- : [rOCCI-cli] An error occurred! Message: Could not match "Link: /network/interface/35ccceb3-9872-44ee-878a-d6298aa11769; occi.networkinterface.gateway=\"Not defined\"; occi.networkinterface.state=\"active\"; occi.networkinterface.address=\"150.165.15.81:10006\"; occi.networkinterface.mac=\"Not defined\"; occi.networkinterface.interface=\"eth0\"; occi.core.id=\"/network/interface/35ccceb3-9872-44ee-878a-d6298aa11769\"; occi.core.target=\"/network/public\"; occi.networkinterface.allocation=\"static\"; occi.core.source=\"/compute/federated_instance_089d406b-f57e-47f8-ae20-b37bf9e319c9\""
/var/lib/gems/1.9.1/gems/occi-core-4.3.2/lib/occi/parser/text.rb:187:in `link_string': Could not match "Link: /network/interface/35ccceb3-9872-44ee-878a-d6298aa11769; occi.networkinterface.gateway=\"Not defined\"; occi.networkinterface.state=\"active\"; occi.networkinterface.address=\"150.165.15.81:10006\"; occi.networkinterface.mac=\"Not defined\"; occi.networkinterface.interface=\"eth0\"; occi.core.id=\"/network/interface/35ccceb3-9872-44ee-878a-d6298aa11769\"; occi.core.target=\"/network/public\"; occi.networkinterface.allocation=\"static\"; occi.core.source=\"/compute/federated_instance_089d406b-f57e-47f8-ae20-b37bf9e319c9\"" (Occi::Errors::ParserInputError)
	from /var/lib/gems/1.9.1/gems/occi-core-4.3.2/lib/occi/parser/text.rb:46:in `block in resource'
	from /var/lib/gems/1.9.1/gems/occi-core-4.3.2/lib/occi/parser/text.rb:58:in `each'
	from /var/lib/gems/1.9.1/gems/occi-core-4.3.2/lib/occi/parser/text.rb:58:in `resource'
	from /var/lib/gems/1.9.1/gems/occi-core-4.3.2/lib/occi/parser.rb:101:in `parse_body_plain'
	from /var/lib/gems/1.9.1/gems/occi-core-4.3.2/lib/occi/parser.rb:86:in `parse_body'
	from /var/lib/gems/1.9.1/gems/occi-core-4.3.2/lib/occi/parser.rb:25:in `parse'
	from /var/lib/gems/1.9.1/gems/occi-api-4.3.4/lib/occi/api/client/http/party_wrappers.rb:112:in `get_process_response'
	from /var/lib/gems/1.9.1/gems/occi-api-4.3.4/lib/occi/api/client/http/party_wrappers.rb:36:in `get'
	from /var/lib/gems/1.9.1/gems/occi-api-4.3.4/lib/occi/api/client/client_http.rb:118:in `describe'
	from /var/lib/gems/1.9.1/gems/occi-api-4.3.4/lib/occi/api/dsl/main_methods.rb:17:in `describe'
	from /var/lib/gems/1.9.1/gems/occi-cli-4.3.3/lib/occi/cli/helpers/describe_helper.rb:7:in `helper_describe'
	from /var/lib/gems/1.9.1/gems/occi-cli-4.3.3/bin/occi:142:in `<top (required)>'
	from /usr/local/bin/occi:19:in `load'
	from /usr/local/bin/occi:19:in `<main>'
```

Do you have any idea what could be happing? It seems to be related to link.

Many thanks!

**Comment by arax** [comment]
Hi @giovannifs ,

the link should look like this (new lines added for readability):
```
Link: </network/public>;
      rel="http://schemas.ogf.org/occi/infrastructure#network";
      self="/network/interface/35ccceb3-9872-44ee-878a-d6298aa11769";
      category="http://schemas.ogf.org/occi/infrastructure#networkinterface http://schemas.ogf.org/occi/infrastructure/networkinterface#ipnetworkinterface";
      occi.networkinterface.state="active";
      occi.networkinterface.address="150.165.15.81:10006";
      occi.networkinterface.interface="eth0";
      occi.core.id="/network/interface/35ccceb3-9872-44ee-878a-d6298aa11769";
      occi.networkinterface.allocation="static"
```
__Notice:__
* `<` and `>` around the `target` (first element)
* `rel` (`target` kind identifier)
* `self` (== `occi.core.id` of the link instance)
* `category` with kind/mixin identifiers of:
  * the link kind
  * associated mixins
* "Not Defined" attributes are skipped ("Not Defined" is not a valid MAC address, for example)
* `source` is implied (the instance that contains this link rendering is the `source`)

I hope this helps.

Cheers

**Comment by giovannifs** [comment]
Hi @arax ,

Many thanks for your feedback.

But I can't describe a resource yet. Could you provide me an example of link that rocci-cli understand?

The link line returned while describing a resource is bellow:  
```
Link: </network/public>; occi.networkinterface.gateway="10.10.0.1"; category="http://schemas.ogf.org/occi/infrastructure#networkinterface http://schemas.ogf.org/occi/infrastructure/networkinterface#ipnetworkinterface"; occi.networkinterface.state="active"; occi.networkinterface.address="150.165.15.81:10014"; self="/network/interface/e2e97258-c376-4ac2-b0ea-b209a8a45ba4"; occi.core.id="/network/interface/e2e97258-c376-4ac2-b0ea-b209a8a45ba4"; occi.networkinterface.interface="eth0"; occi.networkinterface.mac="00:0a:95:9d:68:16"; rel="http://schemas.ogf.org/occi/infrastructure#network"; occi.networkinterface.allocation="static"
```

I removed source and target attributes and added  < >, rel and category attributes. Am I forgetting some attribute? Isn't this the format that rocci-cli expects?

I'll really appreciate your help.

Cheers

**Comment by arax** [comment]
In this case, order is important. You have to provide `<URI>`, `rel`, `self`, `category` and then everything else (attributes).

**Comment by giovannifs** [comment]
Hi @arax ,

Many thanks! I did some progress! :)

Now I'm getting the following error:

```
-> "Category: compute; scheme=\"http://schemas.ogf.org/occi/infrastructure#\"; class=\"kind\"; title=\"Compute Resource\"; rel=\"http://schemas.ogf.org/occi/core#resource\"; location=\"http://localhost:8182/compute/\"; attributes=\"occi.compute.architecture occi.compute.state{immutable} occi.compute.speed occi.compute.memory occi.compute.cores occi.compute.hostname\"; actions=\"http://schemas.ogf.org/occi/infrastructure/compute/action#start http://schemas.ogf.org/occi/infrastructure/compute/action#stop http://schemas.ogf.org/occi/infrastructure/compute/action#restart http://schemas.ogf.org/occi/infrastructure/compute/action#suspend\"\nCategory: m1-small; scheme=\"http://schemas.openstack.org/template/resource#\"; class=\"mixin\"; title=\"Flavor: m1.small \"; rel=\"http://schemas.ogf.org/occi/infrastructure#resource_tpl\"; location=\"http://localhost:8787/m1-small/\"\nCategory: fbc85206-fbcc-4ad9-ae93-54946fdd5df7; scheme=\"http://schemas.openstack.org/template/os#\"; class=\"mixin\"; title=\"Image: cirros-0.3.1-x86_64-uec\"; rel=\"http://schemas.ogf.org/occi/infrastructure#os_tpl\"; location=\"http://localhost:8787/fbc85206-fbcc-4ad9-ae93-54946fdd5df7/\"\nCategory: link; scheme=\"http://schemas.ogf.org/occi/core#\"; class=\"kind\"; title=\"Link\"; rel=\"http://schemas.ogf.org/occi/core#entity\"; location=\"http://localhost:8182/link/\"; attributes=\"occi.core.source occi.core.target\"\nCategory: networkinterface; scheme=\"http://schemas.ogf.org/occi/infrastructure#\"; class=\"kind\"; title=\"A L2 Network Interface\"; rel=\"http://schemas.ogf.org/occi/core#link\"; location=\"http://localhost:8787/network/interface/\"; attributes=\"occi.networkinterface.interface{immutable} occi.networkinterface.mac occi.networkinterface.state{immutable}\"\nLink: </network/public>; rel=\"http://schemas.ogf.org/occi/infrastructure#network\" self=\"/network/interface/ef2cea00-ca99-420e-be11-1fe966e1cdbb\" category=\"http://schemas.ogf.org/occi/infrastructure#networkinterface http://schemas.ogf.org/occi/infrastructure/networkinterface#ipnetworkinterface\" occi.networkinterface.gateway=\"10.10.0.1\"; occi.networkinterface.state=\"active\"; occi.networkinterface.address=\"150.165.15.81:10016\"; occi.networkinterface.mac=\"00:0a:95:9d:68:16\"; occi.networkinterface.interface=\"eth0\"; occi.core.id=\"/network/interface/ef2cea00-ca99-420e-be11-1fe966e1cdbb\"; occi.networkinterface.allocation=\"static\"\nX-OCCI-Attribute: occi.compute.state=\"active\"\nX-OCCI-Attribute: occi.compute.hostname=\"fogbow-instance-6e012457-2610-45d7-962c-b375c2d5cfe4\"\nX-OCCI-Attribute: org.fogbowcloud.request.ssh-username=\"fogbow\"\nX-OCCI-Attribute: occi.compute.memory=\"2.0\"\nX-OCCI-Attribute: org.fogbowcloud.request.extra-ports=\"{}\"\nX-OCCI-Attribute: occi.compute.cores=\"1\"\nX-OCCI-Attribute: org.fogbowcloud.request.ssh-public-address=\"150.165.15.81:10016\"\nX-OCCI-Attribute: occi.core.id=\"01694bc0-28cb-47b1-a838-3a64f4982c42\"\nX-OCCI-Attribute: occi.compute.architecture=\"Not defined\"\nX-OCCI-Attribute: occi.compute.speed=\"Not defined\""
read 2942 bytes
Conn close
D, [2016-01-21T14:16:42.394586 #20180] DEBUG -- : [rOCCI-api] Response from location: "/compute/federated_instance_1bb01fe7-8579-4c62-909c-a763f1639ec6"
D, [2016-01-21T14:16:42.396840 #20180] DEBUG -- : [rOCCI-api] Response should contain kind: "http://schemas.ogf.org/occi/infrastructure#compute"
D, [2016-01-21T14:16:42.397100 #20180] DEBUG -- : [rOCCI-api] Parser call: "text/plain" false Occi::Core::Resource {"content-type"=>["text/plain; charset=UTF-8"], "content-length"=>["2942"], "server"=>["Restlet-Framework/2.2.0"], "accept-ranges"=>["bytes"], "vary"=>["Accept-Charset, Accept-Encoding, Accept-Language, Accept"], "date"=>["Thu, 21 Jan 2016 14:19:44 GMT"]}
D, [2016-01-21T14:16:42.397234 #20180] DEBUG -- : [rOCCI-core] [Occi::Parser] Parsing request data to OCCI Collection
D, [2016-01-21T14:16:42.397402 #20180] DEBUG -- : [rOCCI-core] [Occi::Parser] Parsing headers: []
D, [2016-01-21T14:16:42.397572 #20180] DEBUG -- : [rOCCI-core] [Occi::Parser] Parsing a resource from headers
D, [2016-01-21T14:16:42.397670 #20180] DEBUG -- : [rOCCI-core] [Occi::Parser::Text] Parsing through Occi::Parser::Text.resource
D, [2016-01-21T14:16:42.397878 #20180] DEBUG -- : [rOCCI-core] [Occi::Model] Registering OCCI Core categories enitity, resource and link
D, [2016-01-21T14:16:42.397968 #20180] DEBUG -- : [rOCCI-core] [Occi::Model] Registering category http://schemas.ogf.org/occi/core#entity
D, [2016-01-21T14:16:42.398152 #20180] DEBUG -- : [rOCCI-core] [Occi::Model] Registering category http://schemas.ogf.org/occi/core#resource
D, [2016-01-21T14:16:42.398342 #20180] DEBUG -- : [rOCCI-core] [Occi::Model] Registering category http://schemas.ogf.org/occi/core#link
D, [2016-01-21T14:16:42.400068 #20180] DEBUG -- : [rOCCI-core] [Occi::Core::Attributes] Skipping pattern checks on attributes, turn off the compatibility mode and enable the attribute pattern check in settings!
D, [2016-01-21T14:16:42.400294 #20180] DEBUG -- : [rOCCI-core] [Occi::Parser] Parsing text/plain from body
D, [2016-01-21T14:16:42.400541 #20180] DEBUG -- : [rOCCI-core] [Occi::Model] Registering OCCI Core categories enitity, resource and link
D, [2016-01-21T14:16:42.400636 #20180] DEBUG -- : [rOCCI-core] [Occi::Model] Registering category http://schemas.ogf.org/occi/core#entity
D, [2016-01-21T14:16:42.400807 #20180] DEBUG -- : [rOCCI-core] [Occi::Model] Registering category http://schemas.ogf.org/occi/core#resource
D, [2016-01-21T14:16:42.401782 #20180] DEBUG -- : [rOCCI-core] [Occi::Model] Registering category http://schemas.ogf.org/occi/core#link
D, [2016-01-21T14:16:42.402157 #20180] DEBUG -- : [rOCCI-core] [Occi::Parser::Text] Parsing through Occi::Parser::Text.resource
D, [2016-01-21T14:16:42.402350 #20180] DEBUG -- : [rOCCI-core] [Occi::Model] Registering OCCI Core categories enitity, resource and link
D, [2016-01-21T14:16:42.402437 #20180] DEBUG -- : [rOCCI-core] [Occi::Model] Registering category http://schemas.ogf.org/occi/core#entity
D, [2016-01-21T14:16:42.402596 #20180] DEBUG -- : [rOCCI-core] [Occi::Model] Registering category http://schemas.ogf.org/occi/core#resource
D, [2016-01-21T14:16:42.402780 #20180] DEBUG -- : [rOCCI-core] [Occi::Model] Registering category http://schemas.ogf.org/occi/core#link
D, [2016-01-21T14:16:42.403859 #20180] DEBUG -- : [rOCCI-core] [Occi::Core::Attributes] Skipping pattern checks on attributes, turn off the compatibility mode and enable the attribute pattern check in settings!
D, [2016-01-21T14:16:42.404043 #20180] DEBUG -- : [rOCCI-core] [Occi::Parser::Text] Parsing through Occi::Parser::Text.category
D, [2016-01-21T14:16:42.413206 #20180] DEBUG -- : [rOCCI-core] [Occi::Parser::Text] class "kind" identified as kind
D, [2016-01-21T14:16:42.415229 #20180] DEBUG -- : [rOCCI-core] [Occi::Core::Attributes] Skipping pattern checks on attributes, turn off the compatibility mode and enable the attribute pattern check in settings!
D, [2016-01-21T14:16:42.415366 #20180] DEBUG -- : [rOCCI-core] [Occi::Parser::Text] Parsing through Occi::Parser::Text.category
D, [2016-01-21T14:16:42.419539 #20180] DEBUG -- : [rOCCI-core] [Occi::Parser::Text] class "mixin" identified as mixin
D, [2016-01-21T14:16:42.419815 #20180] DEBUG -- : [rOCCI-core] [Occi::Parser::Text] Parsing through Occi::Parser::Text.category
D, [2016-01-21T14:16:42.424065 #20180] DEBUG -- : [rOCCI-core] [Occi::Parser::Text] class "mixin" identified as mixin
D, [2016-01-21T14:16:42.424319 #20180] DEBUG -- : [rOCCI-core] [Occi::Parser::Text] Parsing through Occi::Parser::Text.category
D, [2016-01-21T14:16:42.429116 #20180] DEBUG -- : [rOCCI-core] [Occi::Parser::Text] class "kind" identified as kind
D, [2016-01-21T14:16:42.429849 #20180] DEBUG -- : [rOCCI-core] [Occi::Core::Attributes] Skipping pattern checks on attributes, turn off the compatibility mode and enable the attribute pattern check in settings!
D, [2016-01-21T14:16:42.430945 #20180] DEBUG -- : [rOCCI-core] [Occi::Parser::Text] Parsing through Occi::Parser::Text.category
D, [2016-01-21T14:16:42.436070 #20180] DEBUG -- : [rOCCI-core] [Occi::Parser::Text] class "kind" identified as kind
D, [2016-01-21T14:16:42.438024 #20180] DEBUG -- : [rOCCI-core] [Occi::Core::Attributes] Skipping pattern checks on attributes, turn off the compatibility mode and enable the attribute pattern check in settings!
D, [2016-01-21T14:16:42.439134 #20180] DEBUG -- : [rOCCI-core] [Occi::Parser::Text] Parsing through Occi::Parser::Text.link_string
D, [2016-01-21T14:16:42.444007 #20180] DEBUG -- : [rOCCI-core] [Occi::Parser::Text] Parsing through Occi::Parser::Text.attribute
D, [2016-01-21T14:16:42.444250 #20180] DEBUG -- : [rOCCI-core] [Occi::Parser::Text] Parsing through Occi::Parser::Text.attribute
D, [2016-01-21T14:16:42.444518 #20180] DEBUG -- : [rOCCI-core] [Occi::Parser::Text] Parsing through Occi::Parser::Text.attribute
D, [2016-01-21T14:16:42.444796 #20180] DEBUG -- : [rOCCI-core] [Occi::Parser::Text] Parsing through Occi::Parser::Text.attribute
D, [2016-01-21T14:16:42.445063 #20180] DEBUG -- : [rOCCI-core] [Occi::Parser::Text] Parsing through Occi::Parser::Text.attribute
D, [2016-01-21T14:16:42.445335 #20180] DEBUG -- : [rOCCI-core] [Occi::Parser::Text] Parsing through Occi::Parser::Text.attribute
D, [2016-01-21T14:16:42.445630 #20180] DEBUG -- : [rOCCI-core] [Occi::Parser::Text] Parsing through Occi::Parser::Text.attribute
D, [2016-01-21T14:16:42.445898 #20180] DEBUG -- : [rOCCI-core] [Occi::Parser::Text] Parsing through Occi::Parser::Text.attribute
D, [2016-01-21T14:16:42.446146 #20180] DEBUG -- : [rOCCI-core] [Occi::Parser::Text] Parsing through Occi::Parser::Text.attribute
F, [2016-01-21T14:16:42.448806 #20180] FATAL -- : [rOCCI-cli] An error occurred! Message: undefined method `links' for #<Occi::Infrastructure::Networkinterface:0x0000000137bc38>
/var/lib/gems/1.9.1/gems/occi-core-4.3.2/lib/occi/parser/text.rb:49:in `block in resource': undefined method `links' for #<Occi::Infrastructure::Networkinterface:0x0000000137bc38> (NoMethodError)
	from /var/lib/gems/1.9.1/gems/occi-core-4.3.2/lib/occi/parser/text.rb:58:in `each'
	from /var/lib/gems/1.9.1/gems/occi-core-4.3.2/lib/occi/parser/text.rb:58:in `resource'
	from /var/lib/gems/1.9.1/gems/occi-core-4.3.2/lib/occi/parser.rb:101:in `parse_body_plain'
	from /var/lib/gems/1.9.1/gems/occi-core-4.3.2/lib/occi/parser.rb:86:in `parse_body'
	from /var/lib/gems/1.9.1/gems/occi-core-4.3.2/lib/occi/parser.rb:25:in `parse'
	from /var/lib/gems/1.9.1/gems/occi-api-4.3.4/lib/occi/api/client/http/party_wrappers.rb:112:in `get_process_response'
	from /var/lib/gems/1.9.1/gems/occi-api-4.3.4/lib/occi/api/client/http/party_wrappers.rb:36:in `get'
	from /var/lib/gems/1.9.1/gems/occi-api-4.3.4/lib/occi/api/client/client_http.rb:118:in `describe'
	from /var/lib/gems/1.9.1/gems/occi-api-4.3.4/lib/occi/api/dsl/main_methods.rb:17:in `describe'
	from /var/lib/gems/1.9.1/gems/occi-cli-4.3.3/lib/occi/cli/helpers/describe_helper.rb:7:in `helper_describe'
	from /var/lib/gems/1.9.1/gems/occi-cli-4.3.3/bin/occi:142:in `<top (required)>'
	from /usr/local/bin/occi:19:in `load'
	from /usr/local/bin/occi:19:in `<main>'
```

The categories and link returned by provider are:
```
Category: compute; scheme="http://schemas.ogf.org/occi/infrastructure#"; class="kind"; title="Compute Resource"; rel="http://schemas.ogf.org/occi/core#resource"; location="http://localhost:8182/compute/"; attributes="occi.compute.architecture occi.compute.state{immutable} occi.compute.speed occi.compute.memory occi.compute.cores occi.compute.hostname"; actions="http://schemas.ogf.org/occi/infrastructure/compute/action#start http://schemas.ogf.org/occi/infrastructure/compute/action#stop http://schemas.ogf.org/occi/infrastructure/compute/action#restart http://schemas.ogf.org/occi/infrastructure/compute/action#suspend"
Category: m1-small; scheme="http://schemas.openstack.org/template/resource#"; class="mixin"; title="Flavor: m1.small "; rel="http://schemas.ogf.org/occi/infrastructure#resource_tpl"; location="http://localhost:8787/m1-small/"
Category: fbc85206-fbcc-4ad9-ae93-54946fdd5df7; scheme="http://schemas.openstack.org/template/os#"; class="mixin"; title="Image: cirros-0.3.1-x86_64-uec"; rel="http://schemas.ogf.org/occi/infrastructure#os_tpl"; location="http://localhost:8787/fbc85206-fbcc-4ad9-ae93-54946fdd5df7/"
Category: link; scheme="http://schemas.ogf.org/occi/core#"; class="kind"; title="Link"; rel="http://schemas.ogf.org/occi/core#entity"; location="http://localhost:8182/link/"; attributes="occi.core.source occi.core.target"
Category: networkinterface; scheme="http://schemas.ogf.org/occi/infrastructure#"; class="kind"; title="A L2 Network Interface"; rel="http://schemas.ogf.org/occi/core#link"; location="http://localhost:8787/network/interface/"; attributes="occi.networkinterface.interface{immutable} occi.networkinterface.mac occi.networkinterface.state{immutable}"
Link: </network/public>; rel="http://schemas.ogf.org/occi/infrastructure#network" self="/network/interface/ef2cea00-ca99-420e-be11-1fe966e1cdbb" category="http://schemas.ogf.org/occi/infrastructure#networkinterface http://schemas.ogf.org/occi/infrastructure/networkinterface#ipnetworkinterface" occi.networkinterface.gateway="10.10.0.1"; occi.networkinterface.state="active"; occi.networkinterface.address="150.165.15.81:10016"; occi.core.id="/network/interface/ef2cea00-ca99-420e-be11-1fe966e1cdbb"; occi.networkinterface.interface="eth0"; occi.networkinterface.mac="00:0a:95:9d:68:16"; occi.networkinterface.allocation="static"
X-OCCI-Attribute: occi.compute.state="active"
X-OCCI-Attribute: occi.compute.hostname="fogbow-instance-6e012457-2610-45d7-962c-b375c2d5cfe4"
X-OCCI-Attribute: org.fogbowcloud.request.ssh-username="fogbow"
X-OCCI-Attribute: occi.compute.memory="2.0"
X-OCCI-Attribute: org.fogbowcloud.request.extra-ports="{}"
X-OCCI-Attribute: occi.compute.cores="1"
X-OCCI-Attribute: org.fogbowcloud.request.ssh-public-address="150.165.15.81:10016"
X-OCCI-Attribute: occi.core.id="01694bc0-28cb-47b1-a838-3a64f4982c42"
X-OCCI-Attribute: occi.compute.architecture="Not defined"
X-OCCI-Attribute: occi.compute.speed="Not defined"
```

Do you have any ideia about what is happing?

Cheers

**Comment by arax** [comment]
Hmm, looks like there are some run-away categories there. An instance rendering MUST contain only one instance (=> one occurrence of `class="kind"`)

These two shouldn't be there:
```
Category: link; scheme="http://schemas.ogf.org/occi/core#"; class="kind"; title="Link"; rel="http://schemas.ogf.org/occi/core#entity"; location="http://localhost:8182/link/"; attributes="occi.core.source occi.core.target"
Category: networkinterface; scheme="http://schemas.ogf.org/occi/infrastructure#"; class="kind"; title="A L2 Network Interface"; rel="http://schemas.ogf.org/occi/core#link"; location="http://localhost:8787/network/interface/"; attributes="occi.networkinterface.interface{immutable} occi.networkinterface.mac occi.networkinterface.state{immutable}"
```

Also, a few semicolons are missing from `Link:`.

**Comment by giovannifs** [comment]
Hi @arax ,

Thank you very much!
It solved the problem.

Cheers
